spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    jpa.properties.hibernate.format_sql: true

#Enable spring data repos 
  data.jpa.repositories.enabled: true
  datasource:
    url: mysql://localhost:3036/irms-service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Ashu@007
    hikari:
      minimumIdle: 2
      maximum-pool-size: 3


server:
  servlet:
    context-path: /irms-service

logging:
  file: /logs/application.log
  level:
    org.springframework: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

