spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    jpa.properties.hibernate.format_sql: true
#Enable spring data repos 
  data.jpa.repositories.enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/irms_service
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 
    hikari:
      minimumIdle: 2
      maximum-pool-size: 3
      
irms-service:
  upload-location: /Users/ashu/Documents/uploaded/

logging:
  file: /logs/application.log
  level:
    org.springframework: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

